package org.betterx.wover.testmod.gametest;

import net.minecraft.core.registries.Registries;
import net.minecraft.gametest.framework.GameTestHelper;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceKey;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.crafting.Recipe;
import net.minecraft.world.item.crafting.RecipeManager;

import java.util.ArrayList;
import java.util.List;

import net.fabricmc.fabric.api.gametest.v1.GameTest;

/**
 * Fabric GameTest for the recipe API: "recipes contributed by the testmod are present in the
 * server {@link RecipeManager} at runtime".
 * <p>
 * The testmod contributes crafting recipes two ways, and both must end up in the running server's
 * recipe manager once the world is up:
 * <ul>
 *   <li>as a committed datapack JSON file under {@code src/testmod/generated/data/.../recipe/}
 *       (test_recipe, generated by {@code TestRecipeProvider}) - this proves datapack recipe
 *       loading;</li>
 *   <li>programmatically via {@code RecipeBuilder.BOOTSTRAP_RECIPES} in {@code TestModWoverRecipe}
 *       (test_diamoan_recipe) - this proves runtime recipe injection through
 *       {@code RecipeRuntimeProviderImpl}.</li>
 * </ul>
 * This test reads the live {@link RecipeManager} back from the server and asserts every expected
 * recipe is present. A missing recipe is a real regression in datapack loading or bootstrap
 * injection.
 */
public class RecipeGameTest {
    // Recipe loaded from the committed datapack JSON file (always-on testmod data).
    private static final String DATAPACK_RECIPE = "wover-recipe-testmod:test_recipe";

    // Recipe injected programmatically at runtime (TestModWoverRecipe via BOOTSTRAP_RECIPES).
    private static final String INJECTED_RECIPE = "wover-recipe-testmod:test_diamoan_recipe";

    @GameTest
    public void testmodRecipesArePresentAtRuntime(GameTestHelper helper) {
        // The RecipeManager is a server-wide, reloadable manager; recipeAccess() on the level
        // returns the same instance the running dedicated/integrated server uses.
        final RecipeManager recipeManager = helper.getLevel().recipeAccess();

        final List<String> failures = new ArrayList<>();

        // Recipes are keyed by ResourceKey<Recipe<?>> in the Registries.RECIPE registry; byKey()
        // returns an empty Optional when the recipe was never loaded, so isPresent() is a robust,
        // meaningful presence check that fails if the recipe is missing.
        if (!hasRecipe(recipeManager, DATAPACK_RECIPE)) {
            failures.add(DATAPACK_RECIPE + ": expected recipe loaded from datapack JSON but it is missing");
        }

        if (!hasRecipe(recipeManager, INJECTED_RECIPE)) {
            failures.add(INJECTED_RECIPE + ": expected recipe injected via BOOTSTRAP_RECIPES but it is missing");
        }

        if (!failures.isEmpty()) {
            final List<String> present = new ArrayList<>();
            recipeManager.getRecipes().forEach(h -> present.add(h.id().location().toString()));
            helper.fail(Component.literal(
                    "Recipe-manager regression:\n - " + String.join("\n - ", failures)
                            + "\n\nRecipes actually present: " + present
            ));
            return;
        }

        helper.succeed();
    }

    private static boolean hasRecipe(RecipeManager recipeManager, String id) {
        final ResourceKey<Recipe<?>> key = ResourceKey.create(
                Registries.RECIPE, ResourceLocation.parse(id)
        );
        return recipeManager.byKey(key).isPresent();
    }
}
