plugins {
    id 'java'
    id 'maven-publish'
    id 'idea'
    id 'eclipse'
    id 'fabric-loom' version "${loom_version}"
    id "me.modmuss50.mod-publish-plugin" version "2.1.1"
}
archivesBaseName = project.archives_base_name
sourceCompatibility = JavaVersion.VERSION_21
targetCompatibility = JavaVersion.VERSION_21


def getDependencies(project, List<String> depNames, configuration) {
    return depNames.iterator().collect {
        project.dependencies.project(path: ":$it", configuration: configuration)
    }
}

apply from: "functions.gradle"
apply from: "common.gradle"
apply from: "helper.gradle"