# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx8G
org.gradle.parallel=true
#Modrinth
modrinth_versions=["1.21.6"]
#CurseForge
curseforge_id=1037172
#Dependencies
required_dependencies=["fabric-api"]
optional_dependencies=["modmenu"]
#`release`, `beta` or `alpha`
release_channel=alpha
#Loom
loom_version=1.10-SNAPSHOT
# Fabric Properties
# check these on https://fabricmc.net/versions.html
minecraft_version=1.21.6
loader_version=0.16.14
fabric_version=0.128.1+1.21.6
# Mod Properties
mod_version=21.6.0
maven_group=org.betterx
archives_base_name=worldweaver
github_base_name=WorldWeaver
# Dependencies
modmenu_version=11.0.1
wunderlib_version=21.6.1