buildscript {
    dependencies {
        classpath 'org.kohsuke:github-api:1.114'
    }

    repositories {
        gradlePluginPortal()
    }
}
def env = System.getenv()

//from https://lowcarbrob.medium.com/android-pro-tip-generating-your-apps-changelog-from-git-inside-build-gradle-19a07533eec4
String generateChangelog() {
    println "Assembeling Changelog ..."
    def lastTag = "git describe --tags --abbrev=0".execute().text.trim()
    def gitLogCmd = "git log $lastTag..HEAD --oneline --no-merges --pretty=format:\"%s\"".execute().text.trim()

    def features = ""
    def fixes = ""
    def changes = ""
    gitLogCmd.eachLine { gitLine ->
        def line = gitLine.substring(1, gitLine.length() - 1)
        if (line.trim().startsWith("[")) {
            def sline = line.split("]", 2)
            if (sline.length == 2) {
                def type = sline[0].trim().toLowerCase().substring(1)
                def comment = sline[1].trim()

                //filter issue links
                if (comment.contains("(")) {
                    def cline = comment.split("\\(", 2)
                    if (cline.length == 2 && cline[1].contains("#")) {
                        comment = cline[0].trim()
                    }
                }

                if (type == "fix" || type == "fixes" || type == "fixed") {
                    fixes += "- $comment \n"
                } else if (type == "feature" || type == "features") {
                    features += "- $comment \n"
                } else if (type == "change" || type == "changes" || type == "changed") {
                    changes += "- $comment \n"
                } else {
                    println "Unknown Type: $type ($line)"
                }
            }
        }

    }
    def changelog = ""
    if (!features.isEmpty()) {
        changelog += "#### Features\n"
        changelog += features.trim()
        changelog += "\n\n"
    }
    if (!changes.isEmpty()) {
        changelog += "#### Changes\n"
        changelog += changes.trim()
        changelog += "\n\n"
    }
    if (!fixes.isEmpty()) {
        changelog += "#### Fixes\n"
        changelog += fixes.trim()
        changelog += "\n\n"
    }

    println "Changelog since $lastTag:\n$changelog"
    return changelog
}

task changelog() {
    group = 'publishing'
    doLast {
        new File(projectDir, "CHANGES.md").text = generateChangelog()
    }
}

def requiredDependencies = evaluate(project.required_dependencies)
def optionalDependencies = evaluate(project.optional_dependencies)

publishMods {
    dryRun = project.hasProperty("dryRun") ? (project.property("dryRun").toString().toLowerCase() in ["true", "", "1", "yes"]) : false
    file = remapJar.archiveFile
    def changes = new File(projectDir, "CHANGES.md")
    changelog = changes.exists() ? changes.getText('UTF-8') : ""

    type = STABLE
    if (project.release_channel == "beta") {
        type = BETA
    } else if (project.release_channel == "alpha") {
        type = ALPHA
    }

    modLoaders.add("fabric")

    def slurper = new groovy.json.JsonSlurper()
    def versions = slurper.parseText(project.modrinth_versions)
    def latestVersion = versions.isEmpty() ? "" : "[${versions.last()}]"

    curseforge {
        projectId = project.curseforge_id

        def cfTokenFile = new File(projectDir, "../CURSEFORGE_TOKEN")
        accessToken = cfTokenFile.exists() ? cfTokenFile.text.trim() : ""

        versions.each { v ->
            minecraftVersions.add(v)
        }

        // Satisfies CurseForge's mandatory "Environment" version group
        client = true
        server = true

        displayName = "${project.archives_base_name}-${project.mod_version} ${latestVersion}"

        requiredDependencies.each { dep ->
            requires(dep)
        }
        optionalDependencies.each { dep ->
            optional(dep)
        }
    }

    modrinth {
        projectId = findProperty('modrinth_id') ?: project.archives_base_name

        def mrTokenFile = new File(projectDir, "../MODRINTH_TOKEN")
        accessToken = mrTokenFile.exists() ? mrTokenFile.text.trim() : ""

        versions.each { v ->
            minecraftVersions.add(v)
        }

        displayName = "${project.archives_base_name}-${project.mod_version}"

        requiredDependencies.each { dep ->
            requires(dep)
        }
        optionalDependencies.each { dep ->
            optional(dep)
        }
    }
}


task nextVersion() {
    group = 'publishing'

    doLast {
        def slurper = new groovy.json.JsonSlurper();
        def projectID = findProperty('modrinth_id') ?: project.archives_base_name
        def inputFile = rootProject.file('modrinth.json')
        def gameVersions = java.net.URLEncoder.encode(project.modrinth_versions, "UTF-8")
        def json = slurper.parseText('[{ "version_number" : "1.0.-1" }]')
        try {
            new URL("https://api.modrinth.com/v2/project/${projectID}/version?&game_versions=${gameVersions}").withInputStream { i -> inputFile.withOutputStream { it << i } }
            json = slurper.parseText(inputFile.text)
        } catch (FileNotFoundException) {
        }
        println(json)
        def version = json[0].version_number

        //increment patch version
        def indexedVersionList = version.split(/\./).toList().withIndex()
        indexedVersionList = indexedVersionList.collect { num, idx -> num.toInteger() }
        indexedVersionList[2] = indexedVersionList[2].value + 1
        def updatedVersion = indexedVersionList.join(".")

        println "\n\n"
        println "------------- CURRENT VERSION -------------"
        println "Last Published Version: " + version
        println "         Game Versions: " + json[0].game_versions
        println "                Status: " + json[0].status
        println "              Featured: " + json[0].featured
        println "            Downloaded: " + json[0].downloads
        println "\n"
        println "-------------- NEXT VERSION ---------------"
        println "Next Version: " + updatedVersion
        println "\n\n"


        def propertiesFile = new File("gradle.properties")
        def newContents = propertiesFile.text.replaceFirst("mod_version=\\d+.\\d+.\\d+", "mod_version=${updatedVersion}")
        propertiesFile.text = newContents

        def rootFabricFile = rootProject.file("src/main/resources/fabric.mod.json")
        def rootFabricFileJson = slurper.parseText(rootFabricFile.text)
        allprojects.each { proj ->
            if (proj.name == 'bclib-legacy' || proj.name == 'wunderlib') {
                println "Ignoring ${proj}"
                return
            }
            println "Updating Version in ${proj}"

            def fabricFile = proj.file("src/main/resources/fabric.mod.json")
            def fabricJson = slurper.parseText(fabricFile.text)
            fabricJson.version = updatedVersion
            fabricJson.depends.minecraft = slurper.parseText(modrinth_versions)
            fabricJson.depends.fabricloader = rootFabricFileJson.depends.fabricloader
            fabricJson.depends['fabric-api'] = rootFabricFileJson.depends['fabric-api']
            fabricJson.depends.java = rootFabricFileJson.depends.java

            fabricFile.text = groovy.json.JsonOutput.prettyPrint(groovy.json.JsonOutput.toJson(fabricJson))
        }
    }
}

import org.kohsuke.github.GHReleaseBuilder
import org.kohsuke.github.GitHub

task github(dependsOn: [build, remapJar, sourcesJar, javadocJar]) {
    group = 'publishing'
    def slurper = new groovy.json.JsonSlurper()
    def apiKey = new File(projectDir, "../GITHUB_TOKEN")

    onlyIf {
        apiKey.exists()
    }

    doLast {
        apiKey = apiKey.text
        def changes = new File(projectDir, "CHANGES.md")
        if (changes.exists()) {
            changes = changes.getText('UTF-8')
        } else {
            changes = ""
        }

        def github = GitHub.connectUsingOAuth(apiKey as String)
        def repository = github.getRepository("quiqueck/" + archivesBaseName)

        def releaseBuilder = new GHReleaseBuilder(repository, version as String)
        releaseBuilder.name("${archivesBaseName}-${version}")
        releaseBuilder.body(changes)
        releaseBuilder.commitish("1.20")

        def ghRelease = releaseBuilder.create()
        ghRelease.uploadAsset(file("${project.buildDir}/libs/${archivesBaseName}-${version}.jar"), "application/java-archive");
        ghRelease.uploadAsset(file("${project.buildDir}/libs/${archivesBaseName}-${version}-sources.jar"), "application/java-archive");
        ghRelease.uploadAsset(file("${project.buildDir}/libs/${archivesBaseName}-${version}-javadoc.jar"), "application/java-archive");

        subprojects.each { sub ->
            ghRelease.uploadAsset(file("${sub.buildDir}/libs/${sub.archivesBaseName}-${version}.jar"), "application/java-archive");
            ghRelease.uploadAsset(file("${sub.buildDir}/libs/${sub.archivesBaseName}-${version}-sources.jar"), "application/java-archive");
        }
    }
}

subprojects {
    apply plugin: 'maven-publish'

    // Ensure the necessary tasks like remapJar exist in each subproject
    afterEvaluate {
        if (project.name == "wunderlib") return
        publishing {
            publications {
                mavenJava(MavenPublication) {
                    from components.java

                    // Customize the group, artifactId, and version for each subproject
                    groupId = group
                    artifactId = project.name
                    version = project.version

                    // Ensure remapJar is included
                    artifact(tasks.named('remapJar').get()) {
                        classifier "remapped-${project.name}"
                        builtBy tasks.named('remapJar').get()
                    }
                }
            }

            repositories {
                maven {
                    def slurper = new groovy.json.JsonSlurper()
                    def apiKey = slurper.parseText(new File(rootProject.projectDir, "../AMBER_TOKEN").text)
                    name = "Ambertation"
                    url = "https://maven.ambertation.de/releases/"
                    credentials {
                        username = apiKey.username
                        password = apiKey.token
                    }
                }
            }
        }
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            def githubName = findProperty('github_base_name') ?: project.archives_base_name
            artifactId = project.archives_base_name
            // add all the jars that should be included when publishing to maven
            artifact(remapJar) {
                builtBy remapJar
            }
            artifact(sourcesJar) {
                builtBy remapSourcesJar
            }

            // Optional POM configuration
            pom {
                name = project.archives_base_name
                url = "https://github.com/quiqueck/${githubName}"

                licenses {
                    license {
                        name = 'The MIT License'
                        url = 'https://opensource.org/licenses/MIT'
                    }
                }

                scm {
                    connection = "scm:git:https://github.com/quiqueck/${githubName}.git"
                    developerConnection = "scm:git:https://github.com/quiqueck/${githubName}.git"
                    url = "https://github.com/quiqueck/${githubName}"
                }

                // Add subprojects as dependencies in the POM
                withXml {
                    def dependenciesNode = asNode().appendNode('dependencies')

                    subprojects.each { subproject ->
                        def dependencyNode = dependenciesNode.appendNode('dependency')


                        dependencyNode.appendNode('artifactId', subproject.name)
                        if (subproject.name == "wunderlib") {
                            dependencyNode.appendNode('groupId', "de.ambertation")
                            dependencyNode.appendNode('version', project.wunderlib_version)
                        } else {
                            dependencyNode.appendNode('groupId', group)
                            dependencyNode.appendNode('version', project.version)
                        }
                        println("Adding dependency: ${subproject.name} -> ${dependencyNode}")
                        dependencyNode.appendNode('scope', 'compile')
                    }
                }
            }
        }
    }
    repositories {
        maven {
            def slurper = new groovy.json.JsonSlurper();
            def apiKey = slurper.parseText(new File(projectDir, "../AMBER_TOKEN").text)
            println "\nPublishing ${project.archives_base_name} to Maven..."
            name = "Ambertation"
            url = "https://maven.ambertation.de/releases/"
            credentials {
                username = apiKey.username
                password = apiKey.token
            }
        }
    }
}