pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        mavenCentral()
        gradlePluginPortal()
    }
}
rootProject.name = 'world-weaver'
//include 'bclib-legacy'

apply from: "module-include.gradle"
ext.knownWoverModules.each { module ->
    include module
}

apply from: "common-settings.gradle"

// #### Custom Settings ####

// Change the next line to disable local lib loading, even if the sibling folder exists
def allowLocalLibUse = true

// #### Logic ####
includeLocalLib('wunderlib', '../WunderLib', './wunderlib-composit.gradle', allowLocalLibUse)
