base.archivesName = "wover-datagen-api"

ext {
    baseNamespace = "datagen"
    baseClass = "WoverDatagen"
}

dependencies {
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
}

loom {
    accessWidenerPath = file('src/main/resources/wover.datagen.accesswidener')
}

moduleDependencies(project, ['wover-core-api'])