base.archivesName = "wover-ui-api"

ext {
    baseNamespace = "ui"
    baseClass = "WoverUi"
}

dependencies {
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
}

loom {
    accessWidenerPath = file('src/main/resources/wover.ui.accesswidener')
}

moduleDependencies(project, ['wover-core-api', 'wover-event-api'])