base.archivesName = "wover-core-api"
ext {
    baseNamespace = "core"
    baseClass = "WoverCore"
}
dependencies {
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
}


loom {
    accessWidenerPath = file('src/main/resources/wover.core.accesswidener')
}

moduleDependencies(project, ['wover-common-api'])