package de.ambertation.wover.testmod.gametest;

import net.minecraft.advancements.AdvancementHolder;
import net.minecraft.advancements.AdvancementNode;
import net.minecraft.advancements.CriteriaTriggers;
import net.minecraft.advancements.Criterion;
import net.minecraft.advancements.criterion.RecipeUnlockedTrigger;
import net.minecraft.core.registries.Registries;
import net.minecraft.gametest.framework.GameTestHelper;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.Identifier;
import net.minecraft.resources.ResourceKey;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.ServerAdvancementManager;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.item.crafting.Recipe;
import net.minecraft.world.item.crafting.RecipeHolder;
import net.minecraft.world.item.crafting.RecipeManager;

import java.util.ArrayList;
import java.util.List;

import net.fabricmc.fabric.api.gametest.v1.GameTest;

/**
 * Fabric GameTest for the recipe API: "recipes contributed by the testmod are present in the
 * server {@link RecipeManager} at runtime".
 * <p>
 * The testmod contributes crafting recipes two ways, and both must end up in the running server's
 * recipe manager once the world is up:
 * <ul>
 *   <li>as a committed datapack JSON file under {@code src/testmod/generated/data/.../recipe/}
 *       (test_recipe, generated by {@code TestRecipeProvider}) - this proves datapack recipe
 *       loading;</li>
 *   <li>programmatically via {@code RecipeBuilder.BOOTSTRAP_RECIPES} in {@code TestModWoverRecipe}
 *       (test_diamoan_recipe) - this proves runtime recipe injection through
 *       {@code RecipeRuntimeProviderImpl}.</li>
 * </ul>
 * This test reads the live {@link RecipeManager} back from the server and asserts every expected
 * recipe is present. A missing recipe is a real regression in datapack loading or bootstrap
 * injection.
 */
public class RecipeGameTest {
    // Recipe loaded from the committed datapack JSON file (always-on testmod data).
    private static final String DATAPACK_RECIPE = "wover-recipe-testmod:test_recipe";

    // Recipe injected programmatically at runtime (TestModWoverRecipe via BOOTSTRAP_RECIPES).
    private static final String INJECTED_RECIPE = "wover-recipe-testmod:test_diamoan_recipe";

    @GameTest
    public void testmodRecipesArePresentAtRuntime(GameTestHelper helper) {
        // The RecipeManager is a server-wide, reloadable manager; recipeAccess() on the level
        // returns the same instance the running dedicated/integrated server uses.
        final RecipeManager recipeManager = helper.getLevel().recipeAccess();

        final List<String> failures = new ArrayList<>();

        // Recipes are keyed by ResourceKey<Recipe<?>> in the Registries.RECIPE registry; byKey()
        // returns an empty Optional when the recipe was never loaded, so isPresent() is a robust,
        // meaningful presence check that fails if the recipe is missing.
        if (!hasRecipe(recipeManager, DATAPACK_RECIPE)) {
            failures.add(DATAPACK_RECIPE + ": expected recipe loaded from datapack JSON but it is missing");
        }

        if (!hasRecipe(recipeManager, INJECTED_RECIPE)) {
            failures.add(INJECTED_RECIPE + ": expected recipe injected via BOOTSTRAP_RECIPES but it is missing");
        }

        if (!failures.isEmpty()) {
            final List<String> present = new ArrayList<>();
            recipeManager.getRecipes().forEach(h -> present.add(h.id().identifier().toString()));
            helper.fail(Component.literal(
                    "Recipe-manager regression:\n - " + String.join("\n - ", failures)
                            + "\n\nRecipes actually present: " + present
            ));
            return;
        }

        helper.succeed();
    }

    private static boolean hasRecipe(RecipeManager recipeManager, String id) {
        final ResourceKey<Recipe<?>> key = ResourceKey.create(
                Registries.RECIPE, Identifier.parse(id)
        );
        return recipeManager.byKey(key).isPresent();
    }

    // The unlock advancement RecipeUnlockAdvancementBuilder mints for INJECTED_RECIPE: the recipe id with
    // "recipes/<category folder>/" prefixed to its path. The testmod recipe leaves the category at its
    // default, RecipeCategory.MISC, whose folder name is "misc".
    private static final String UNLOCK_ADVANCEMENT =
            "wover-recipe-testmod:recipes/misc/test_diamoan_recipe";

    // Every recipe advancement vanilla generates hangs under this root, which vanilla's own datapack ships.
    private static final Identifier ROOT_RECIPE_ADVANCEMENT =
            Identifier.withDefaultNamespace("recipes/root");

    // The criterion name RecipeUnlockAdvancementBuilder uses for the minecraft:recipe_unlocked trigger.
    private static final String HAS_THE_RECIPE = "has_the_recipe";

    /**
     * Asserts that a recipe contributed at runtime through {@code RecipeBuilder.BOOTSTRAP_RECIPES} gets the
     * same unlock advancement a datapack recipe gets, and that the advancement really works.
     * <p>
     * The {@code AdvancementHolder} that every vanilla recipe builder hands to {@code RecipeOutput#accept}
     * used to be discarded on the runtime path, so these recipes never appeared in the recipe book unless the
     * player was given them with {@code /recipe give}. This test pins the fix down at every level rather than
     * just checking that the advancement object exists:
     * <ol>
     *   <li>the advancement is in the live {@link ServerAdvancementManager} and in its tree, parented under
     *       {@code minecraft:recipes/root} exactly like a datapack recipe's advancement;</li>
     *   <li>its {@code has_the_recipe} criterion is a {@code minecraft:recipe_unlocked} trigger that actually
     *       matches the contributed recipe;</li>
     *   <li>its reward grants the recipe;</li>
     *   <li>and, end to end: firing the trigger for a fresh player completes the advancement, whose reward
     *       puts the recipe into that player's recipe book.</li>
     * </ol>
     */
    // makeMockServerPlayerInLevel() is @Deprecated(forRemoval = true), but it is the only helper that hands
    // out a fully placed ServerPlayer (PlayerList#placeNewPlayer, hence a real PlayerAdvancements and
    // ServerRecipeBook); makeMockPlayer(GameType) returns a bare Player that has neither. Vanilla offers no
    // replacement, so the deprecation is accepted here.
    @SuppressWarnings("removal")
    @GameTest
    public void injectedRecipeHasWorkingUnlockAdvancement(GameTestHelper helper) {
        final MinecraftServer server = helper.getLevel().getServer();
        final List<String> failures = new ArrayList<>();

        final ResourceKey<Recipe<?>> recipeKey = ResourceKey.create(
                Registries.RECIPE, Identifier.parse(INJECTED_RECIPE)
        );
        final RecipeHolder<?> recipeHolder = server.getRecipeManager().byKey(recipeKey).orElse(null);
        if (recipeHolder == null) {
            helper.fail(Component.literal(
                    INJECTED_RECIPE + ": the runtime-injected recipe is missing, so its unlock advancement "
                            + "cannot be tested at all"
            ));
            return;
        }

        final Identifier advancementId = Identifier.parse(UNLOCK_ADVANCEMENT);
        final ServerAdvancementManager advancements = server.getAdvancements();
        final AdvancementHolder advancement = advancements.get(advancementId);

        if (advancement == null) {
            final List<String> recipeAdvancements = new ArrayList<>();
            advancements.getAllAdvancements()
                        .forEach(a -> {
                            if (a.id().getPath().startsWith("recipes/")) {
                                recipeAdvancements.add(a.id().toString());
                            }
                        });
            helper.fail(Component.literal(
                    UNLOCK_ADVANCEMENT + ": runtime-contributed recipes must get an unlock advancement, but "
                            + "none was registered.\n\nRecipe advancements actually present: "
                            + recipeAdvancements
            ));
            return;
        }

        // (1) part of the advancement tree, under the same root vanilla's recipe advancements use.
        final AdvancementNode node = advancements.tree().get(advancementId);
        if (node == null) {
            failures.add(UNLOCK_ADVANCEMENT + ": registered, but never inserted into the advancement tree");
        } else if (node.parent() == null || !ROOT_RECIPE_ADVANCEMENT.equals(node.parent().holder().id())) {
            failures.add(UNLOCK_ADVANCEMENT + ": expected parent " + ROOT_RECIPE_ADVANCEMENT
                    + " but got " + (node.parent() == null ? "<none>" : node.parent().holder().id()));
        }

        // (2) the recipe_unlocked criterion matches the contributed recipe.
        final Criterion<?> criterion = advancement.value().criteria().get(HAS_THE_RECIPE);
        if (criterion == null) {
            failures.add(UNLOCK_ADVANCEMENT + ": missing the '" + HAS_THE_RECIPE + "' criterion, so the "
                    + "recipe book can never unlock this recipe through minecraft:recipe_unlocked");
        } else if (!(criterion.triggerInstance() instanceof RecipeUnlockedTrigger.TriggerInstance instance)) {
            failures.add(UNLOCK_ADVANCEMENT + ": '" + HAS_THE_RECIPE + "' is not a recipe_unlocked trigger but "
                    + criterion.triggerInstance().getClass().getName());
        } else if (!instance.matches(recipeHolder)) {
            failures.add(UNLOCK_ADVANCEMENT + ": the recipe_unlocked trigger does not match " + INJECTED_RECIPE
                    + " - it references " + instance.recipe());
        }

        // (3) completing the advancement hands the recipe out.
        if (!advancement.value().rewards().recipes().contains(recipeKey)) {
            failures.add(UNLOCK_ADVANCEMENT + ": its rewards do not grant " + INJECTED_RECIPE
                    + " (rewards: " + advancement.value().rewards().recipes() + ")");
        }

        // (4) end to end, on a real ServerPlayer: firing the trigger must land the recipe in the recipe book.
        final ServerPlayer player = helper.makeMockServerPlayerInLevel();
        if (player.getRecipeBook().contains(recipeKey)) {
            failures.add(INJECTED_RECIPE + ": a fresh player already knows the recipe, so the end-to-end "
                    + "check below would prove nothing");
        } else {
            CriteriaTriggers.RECIPE_UNLOCKED.trigger(player, recipeHolder);
            if (!player.getRecipeBook().contains(recipeKey)) {
                failures.add(INJECTED_RECIPE + ": firing minecraft:recipe_unlocked did not unlock the recipe "
                        + "for the player - the advancement exists but does not fire");
            }
        }

        if (!failures.isEmpty()) {
            helper.fail(Component.literal(
                    "Runtime recipe unlock-advancement regression:\n - " + String.join("\n - ", failures)
            ));
            return;
        }

        helper.succeed();
    }
}
