base.archivesName = "wover-recipe-api"

ext {
    baseNamespace = "recipe"
    baseClass = "LibWoverRecipe"
}

dependencies {
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
}

loom {
    accessWidenerPath = file('src/main/resources/wover-recipe.accesswidener')
}

moduleDependencies(project, ['wover-core-api', 'wover-item-api', 'wover-block-api', 'wover-event-api', 'wover-tag-api', 'wover-datagen-api'])